### ISSUE TITLE
Docker Overview problem

### ISSUE THREAD

**Issue by teemuniiranen** [monitoringartist/grafana-zabbix-dashboards#1]
What could be wrong when I can see only "CPU time" and "Used RSS Memory" graphs? I can see for example status of containers in Zabbix but graph in Grafana does not get any data points.

**Comment by jangaraj** [comment]
Edit those graphs and change the query. Maybe you have a different metric/device group/... naming convention.

**Comment by teemuniiranen** [comment]
The setup is the out of the box provided by dockbix-xxl stack. Need to take a closer look if something still differs. I tried also with play.monitoringart.com agent but result the was the same.
